### ISSUE TITLE
invalid-meta bootstrap-html5sortable is missing "main" entry in bower.json

### ISSUE THREAD

**Issue by CamiloBernal** [psfpro/bootstrap-html5sortable#1]
Hello, first of all, thank you very much for this great utility.

When I try to use to install this update bower bootstrap-html5sortable in my project, this error: `invalid-meta-html5sortable is missing bootstrap 'main' entry in bower.json`.

So I can interpret this error and what I've read in various forums, I think that the error message is produced because bower bower.json can not find the file in the archives of the git repository. Although not really know if this question or not.

Thank add bower.json properly file in the git repository.

Thank you.

**Comment by psfpro** [comment]
Added bower.json. Try now should be good.

**Comment by CamiloBernal** [comment]
Yeah, it works. Thank you.
